### ISSUE TITLE
More AlgPuzzleVQA generation script

### ISSUE THREAD

**Issue by hanxiaotian** [declare-lab/LLM-PuzzleTest#1]
Hi,

Thanks for sharing the whole dataset of AlgPuzzleVQA and corresponding generation script. 
I checked and found that there are totally 18 generation categories, however only 10 generation scripts are provided under generation folder. 
Could you please share the whole 18 generation scripts? 

Thanks!

**Comment by deepanwayx** [comment]
I will release the rest of the scripts soon.

**Comment by hanxiaotian** [comment]
Thanks for your great help
